{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
{{ include "sysdig-stackdriver-bridge.labels" . | indent 4 }}
  {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
  {{- end }}
type: Opaque
data:
  key.json: {{ .Values.secret.data | b64enc | quote }}
{{- end }}
